# Generated by Django 4.1.7 on 2023-05-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_factor_short_name'),
        ('risk_assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='aRating',
            field=models.ForeignKey(db_column='aRating', on_delete=django.db.models.deletion.RESTRICT, related_name='slope', to='factors.factorrating'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='sRating',
            field=models.ForeignKey(db_column='sRating', on_delete=django.db.models.deletion.RESTRICT, related_name='soil_mass', to='factors.factorrating'),
        ),
    ]
