# Generated by Django 4.1.7 on 2023-05-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessments', '0002_alter_riskassessment_arating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
