# Generated by Django 4.1.7 on 2023-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='short_name',
            field=models.CharField(default=1.1, max_length=20),
            preserve_default=False,
        ),
    ]
