# Generated by Django 4.1.7 on 2023-05-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='municipalities.municipality')),
            ],
            options={
                'db_table': 'barangays',
            },
        ),
    ]
